In [1]:
import numpy

In [2]:
import pandas

In [3]:
import pgmpy

In [4]:
data = pandas.read_csv("Bank_Defaults.csv")

In [5]:
data

age            job   marital  education default  balance housing loan  \
0      30     unemployed   married    primary      no     1787      no   no   
1      33       services   married  secondary      no     4789     yes  yes   
2      35     management    single   tertiary      no     1350     yes   no   
3      30     management   married   tertiary      no     1476     yes  yes   
4      59    blue-collar   married  secondary      no        0     yes   no   
5      35     management    single   tertiary      no      747      no   no   
6      36  self-employed   married   tertiary      no      307     yes   no   
7      39     technician   married  secondary      no      147     yes   no   
8      41   entrepreneur   married   tertiary      no      221     yes   no   
9      43       services   married    primary      no      -88     yes  yes   
10     39       services   married  secondary      no     9374     yes   no   
11     43         admin.   married  secondary      no      264     yes   no   
12     36     technician   married   tertiary      no     1109      no   no   
13     20        student    single  secondary      no      502      no   no   
14     31    blue-collar   married  secondary      no      360     yes  yes   
15     40     management   married   tertiary      no      194      no  yes   
16     56     technician   married  secondary      no     4073      no   no   
17     37         admin.    single   tertiary      no     2317     yes   no   
18     25    blue-collar    single    primary      no     -221     yes   no   
19     31       services   married  secondary      no      132      no   no   
20     38     management  divorced    unknown      no        0     yes   no   
21     42     management  divorced   tertiary      no       16      no   no   
22     44       services    single  secondary      no      106      no   no   
23     44   entrepreneur   married  secondary      no       93      no   no   
24     26      housemaid   married   tertiary      no      543      no   no   
25     41     management   married   tertiary      no     5883      no   no   
26     55    blue-collar   married    primary      no      627     yes   no   
27     67        retired   married    unknown      no      696      no   no   
28     56  self-employed   married  secondary      no      784      no  yes   
29     53         admin.   married  secondary      no      105      no  yes   
...   ...            ...       ...        ...     ...      ...     ...  ...   
4491   35    blue-collar    single  secondary      no        0     yes   no   
4492   32     technician    single  secondary      no      309     yes  yes   
4493   28     technician    single   tertiary      no        0     yes   no   
4494   26     technician    single  secondary      no      668     yes   no   
4495   48     management   married   tertiary      no     1175     yes   no   
4496   30    blue-collar    single  secondary      no      363      no   no   
4497   31   entrepreneur    single   tertiary      no       38      no   no   
4498   31     management   married   tertiary      no     1183     yes   no   
4499   45    blue-collar  divorced    primary      no      942      no   no   
4500   38         admin.   married  secondary      no     4196     yes   no   
4501   34     management   married   tertiary      no      297     yes   no   
4502   42       services   married  secondary      no      -91     yes  yes   
4503   60  self-employed   married    primary      no      362      no  yes   
4504   42    blue-collar    single  secondary      no     1080     yes  yes   
4505   32         admin.    single  secondary      no      620     yes   no   
4506   42     unemployed  divorced   tertiary      no     -166      no   no   
4507   33       services   married  secondary      no      288     yes   no   
4508   42         admin.   married    unknown      no      642     yes  yes   
4509   51     technician   married   tertiary      no   

In [6]:
data['default'] = data['default'].astype('category')
data['default'] = data['default'].cat.codes

In [7]:
data

age            job   marital  education  default  balance housing loan  \
0      30     unemployed   married    primary        0     1787      no   no   
1      33       services   married  secondary        0     4789     yes  yes   
2      35     management    single   tertiary        0     1350     yes   no   
3      30     management   married   tertiary        0     1476     yes  yes   
4      59    blue-collar   married  secondary        0        0     yes   no   
5      35     management    single   tertiary        0      747      no   no   
6      36  self-employed   married   tertiary        0      307     yes   no   
7      39     technician   married  secondary        0      147     yes   no   
8      41   entrepreneur   married   tertiary        0      221     yes   no   
9      43       services   married    primary        0      -88     yes  yes   
10     39       services   married  secondary        0     9374     yes   no   
11     43         admin.   married  secondary        0      264     yes   no   
12     36     technician   married   tertiary        0     1109      no   no   
13     20        student    single  secondary        0      502      no   no   
14     31    blue-collar   married  secondary        0      360     yes  yes   
15     40     management   married   tertiary        0      194      no  yes   
16     56     technician   married  secondary        0     4073      no   no   
17     37         admin.    single   tertiary        0     2317     yes   no   
18     25    blue-collar    single    primary        0     -221     yes   no   
19     31       services   married  secondary        0      132      no   no   
20     38     management  divorced    unknown        0        0     yes   no   
21     42     management  divorced   tertiary        0       16      no   no   
22     44       services    single  secondary        0      106      no   no   
23     44   entrepreneur   married  secondary        0       93      no   no   
24     26      housemaid   married   tertiary        0      543      no   no   
25     41     management   married   tertiary        0     5883      no   no   
26     55    blue-collar   married    primary        0      627     yes   no   
27     67        retired   married    unknown        0      696      no   no   
28     56  self-employed   married  secondary        0      784      no  yes   
29     53         admin.   married  secondary        0      105      no  yes   
...   ...            ...       ...        ...      ...      ...     ...  ...   
4491   35    blue-collar    single  secondary        0        0     yes   no   
4492   32     technician    single  secondary        0      309     yes  yes   
4493   28     technician    single   tertiary        0        0     yes   no   
4494   26     technician    single  secondary        0      668     yes   no   
4495   48     management   married   tertiary        0     1175     yes   no   
4496   30    blue-collar    single  secondary        0      363      no   no   
4497   31   entrepreneur    single   tertiary        0       38      no   no   
4498   31     management   married   tertiary        0     1183     yes   no   
4499   45    blue-collar  divorced    primary        0      942      no   no   
4500   38         admin.   married  secondary        0     4196     yes   no   
4501   34     management   married   tertiary        0      297     yes   no   
4502   42       services   married  secondary        0      -91     yes  yes   
4503   60  self-employed   married    primary        0      362      no  yes   
4504   42    blue-collar    single  secondary        0     1080     yes  yes   
4505   32         admin.    single  secondary        0      620     yes   no   
4506   42     unemployed  divorced   tertiary        0     -166      no   no   
4507   33       services   married  secondary        0      288     yes   no   
4508   42         admin.   married    unknown        0      642     yes  yes   
4509  

In [8]:
data['marital'] = data['marital'].astype('category')
data['marital'] = data['marital'].cat.codes
data

age            job  marital  education  default  balance housing loan  \
0      30     unemployed        1    primary        0     1787      no   no   
1      33       services        1  secondary        0     4789     yes  yes   
2      35     management        2   tertiary        0     1350     yes   no   
3      30     management        1   tertiary        0     1476     yes  yes   
4      59    blue-collar        1  secondary        0        0     yes   no   
5      35     management        2   tertiary        0      747      no   no   
6      36  self-employed        1   tertiary        0      307     yes   no   
7      39     technician        1  secondary        0      147     yes   no   
8      41   entrepreneur        1   tertiary        0      221     yes   no   
9      43       services        1    primary        0      -88     yes  yes   
10     39       services        1  secondary        0     9374     yes   no   
11     43         admin.        1  secondary        0      264     yes   no   
12     36     technician        1   tertiary        0     1109      no   no   
13     20        student        2  secondary        0      502      no   no   
14     31    blue-collar        1  secondary        0      360     yes  yes   
15     40     management        1   tertiary        0      194      no  yes   
16     56     technician        1  secondary        0     4073      no   no   
17     37         admin.        2   tertiary        0     2317     yes   no   
18     25    blue-collar        2    primary        0     -221     yes   no   
19     31       services        1  secondary        0      132      no   no   
20     38     management        0    unknown        0        0     yes   no   
21     42     management        0   tertiary        0       16      no   no   
22     44       services        2  secondary        0      106      no   no   
23     44   entrepreneur        1  secondary        0       93      no   no   
24     26      housemaid        1   tertiary        0      543      no   no   
25     41     management        1   tertiary        0     5883      no   no   
26     55    blue-collar        1    primary        0      627     yes   no   
27     67        retired        1    unknown        0      696      no   no   
28     56  self-employed        1  secondary        0      784      no  yes   
29     53         admin.        1  secondary        0      105      no  yes   
...   ...            ...      ...        ...      ...      ...     ...  ...   
4491   35    blue-collar        2  secondary        0        0     yes   no   
4492   32     technician        2  secondary        0      309     yes  yes   
4493   28     technician        2   tertiary        0        0     yes   no   
4494   26     technician        2  secondary        0      668     yes   no   
4495   48     management        1   tertiary        0     1175     yes   no   
4496   30    blue-collar        2  secondary        0      363      no   no   
4497   31   entrepreneur        2   tertiary        0       38      no   no   
4498   31     management        1   tertiary        0     1183     yes   no   
4499   45    blue-collar        0    primary        0      942      no   no   
4500   38         admin.        1  secondary        0     4196     yes   no   
4501   34     management        1   tertiary        0      297     yes   no   
4502   42       services        1  secondary        0      -91     yes  yes   
4503   60  self-employed        1    primary        0      362      no  yes   
4504   42    blue-collar        2  secondary        0     1080     yes  yes   
4505   32         admin.        2  secondary        0      620     yes   no   
4506   42     unemployed        0   tertiary        0     -166      no   no   
4507   33       services        1  secondary        0      288     yes   no   
4508   42         admin.        1    unknown        0      642     yes  yes   
4509   51     technician        1   tertiary        0   

In [9]:
data['education'] = data['education'].astype('category')
data['education'] = data['education'].cat.codes
data

age            job  marital  education  default  balance housing loan  \
0      30     unemployed        1          0        0     1787      no   no   
1      33       services        1          1        0     4789     yes  yes   
2      35     management        2          2        0     1350     yes   no   
3      30     management        1          2        0     1476     yes  yes   
4      59    blue-collar        1          1        0        0     yes   no   
5      35     management        2          2        0      747      no   no   
6      36  self-employed        1          2        0      307     yes   no   
7      39     technician        1          1        0      147     yes   no   
8      41   entrepreneur        1          2        0      221     yes   no   
9      43       services        1          0        0      -88     yes  yes   
10     39       services        1          1        0     9374     yes   no   
11     43         admin.        1          1        0      264     yes   no   
12     36     technician        1          2        0     1109      no   no   
13     20        student        2          1        0      502      no   no   
14     31    blue-collar        1          1        0      360     yes  yes   
15     40     management        1          2        0      194      no  yes   
16     56     technician        1          1        0     4073      no   no   
17     37         admin.        2          2        0     2317     yes   no   
18     25    blue-collar        2          0        0     -221     yes   no   
19     31       services        1          1        0      132      no   no   
20     38     management        0          3        0        0     yes   no   
21     42     management        0          2        0       16      no   no   
22     44       services        2          1        0      106      no   no   
23     44   entrepreneur        1          1        0       93      no   no   
24     26      housemaid        1          2        0      543      no   no   
25     41     management        1          2        0     5883      no   no   
26     55    blue-collar        1          0        0      627     yes   no   
27     67        retired        1          3        0      696      no   no   
28     56  self-employed        1          1        0      784      no  yes   
29     53         admin.        1          1        0      105      no  yes   
...   ...            ...      ...        ...      ...      ...     ...  ...   
4491   35    blue-collar        2          1        0        0     yes   no   
4492   32     technician        2          1        0      309     yes  yes   
4493   28     technician        2          2        0        0     yes   no   
4494   26     technician        2          1        0      668     yes   no   
4495   48     management        1          2        0     1175     yes   no   
4496   30    blue-collar        2          1        0      363      no   no   
4497   31   entrepreneur        2          2        0       38      no   no   
4498   31     management        1          2        0     1183     yes   no   
4499   45    blue-collar        0          0        0      942      no   no   
4500   38         admin.        1          1        0     4196     yes   no   
4501   34     management        1          2        0      297     yes   no   
4502   42       services        1          1        0      -91     yes  yes   
4503   60  self-employed        1          0        0      362      no  yes   
4504   42    blue-collar        2          1        0     1080     yes  yes   
4505   32         admin.        2          1        0      620     yes   no   
4506   42     unemployed        0          2        0     -166      no   no   
4507   33       services        1          1        0      288     yes   no   
4508   42         admin.        1          3        0      642     yes  yes   
4509   51     technician        1          2        0   

In [10]:
data.default.unique()

array([0, 1], dtype=int64)

In [11]:
data.marital.unique()

array([1, 2, 0], dtype=int64)

In [12]:
data.education.unique()

array([0, 1, 2, 3], dtype=int64)

In [13]:
data['housing'] = data['housing'].astype('category')
data['housing'] = data['housing'].cat.codes
data

age            job  marital  education  default  balance  housing loan  \
0      30     unemployed        1          0        0     1787        0   no   
1      33       services        1          1        0     4789        1  yes   
2      35     management        2          2        0     1350        1   no   
3      30     management        1          2        0     1476        1  yes   
4      59    blue-collar        1          1        0        0        1   no   
5      35     management        2          2        0      747        0   no   
6      36  self-employed        1          2        0      307        1   no   
7      39     technician        1          1        0      147        1   no   
8      41   entrepreneur        1          2        0      221        1   no   
9      43       services        1          0        0      -88        1  yes   
10     39       services        1          1        0     9374        1   no   
11     43         admin.        1          1        0      264        1   no   
12     36     technician        1          2        0     1109        0   no   
13     20        student        2          1        0      502        0   no   
14     31    blue-collar        1          1        0      360        1  yes   
15     40     management        1          2        0      194        0  yes   
16     56     technician        1          1        0     4073        0   no   
17     37         admin.        2          2        0     2317        1   no   
18     25    blue-collar        2          0        0     -221        1   no   
19     31       services        1          1        0      132        0   no   
20     38     management        0          3        0        0        1   no   
21     42     management        0          2        0       16        0   no   
22     44       services        2          1        0      106        0   no   
23     44   entrepreneur        1          1        0       93        0   no   
24     26      housemaid        1          2        0      543        0   no   
25     41     management        1          2        0     5883        0   no   
26     55    blue-collar        1          0        0      627        1   no   
27     67        retired        1          3        0      696        0   no   
28     56  self-employed        1          1        0      784        0  yes   
29     53         admin.        1          1        0      105        0  yes   
...   ...            ...      ...        ...      ...      ...      ...  ...   
4491   35    blue-collar        2          1        0        0        1   no   
4492   32     technician        2          1        0      309        1  yes   
4493   28     technician        2          2        0        0        1   no   
4494   26     technician        2          1        0      668        1   no   
4495   48     management        1          2        0     1175        1   no   
4496   30    blue-collar        2          1        0      363        0   no   
4497   31   entrepreneur        2          2        0       38        0   no   
4498   31     management        1          2        0     1183        1   no   
4499   45    blue-collar        0          0        0      942        0   no   
4500   38         admin.        1          1        0     4196        1   no   
4501   34     management        1          2        0      297        1   no   
4502   42       services        1          1        0      -91        1  yes   
4503   60  self-employed        1          0        0      362        0  yes   
4504   42    blue-collar        2          1        0     1080        1  yes   
4505   32         admin.        2          1        0      620        1   no   
4506   42     unemployed        0          2        0     -166        0   no   
4507   33       services        1          1        0      288        1   no   
4508   42         admin.        1          3        0      642        1  yes   
4509  

In [14]:
data.housing.unique()

array([0, 1], dtype=int64)

In [15]:
data['loan'] = data['loan'].astype('category')
data['loan'] = data['loan'].cat.codes
data

age            job  marital  education  default  balance  housing  loan  \
0      30     unemployed        1          0        0     1787        0     0   
1      33       services        1          1        0     4789        1     1   
2      35     management        2          2        0     1350        1     0   
3      30     management        1          2        0     1476        1     1   
4      59    blue-collar        1          1        0        0        1     0   
5      35     management        2          2        0      747        0     0   
6      36  self-employed        1          2        0      307        1     0   
7      39     technician        1          1        0      147        1     0   
8      41   entrepreneur        1          2        0      221        1     0   
9      43       services        1          0        0      -88        1     1   
10     39       services        1          1        0     9374        1     0   
11     43         admin.        1          1        0      264        1     0   
12     36     technician        1          2        0     1109        0     0   
13     20        student        2          1        0      502        0     0   
14     31    blue-collar        1          1        0      360        1     1   
15     40     management        1          2        0      194        0     1   
16     56     technician        1          1        0     4073        0     0   
17     37         admin.        2          2        0     2317        1     0   
18     25    blue-collar        2          0        0     -221        1     0   
19     31       services        1          1        0      132        0     0   
20     38     management        0          3        0        0        1     0   
21     42     management        0          2        0       16        0     0   
22     44       services        2          1        0      106        0     0   
23     44   entrepreneur        1          1        0       93        0     0   
24     26      housemaid        1          2        0      543        0     0   
25     41     management        1          2        0     5883        0     0   
26     55    blue-collar        1          0        0      627        1     0   
27     67        retired        1          3        0      696        0     0   
28     56  self-employed        1          1        0      784        0     1   
29     53         admin.        1          1        0      105        0     1   
...   ...            ...      ...        ...      ...      ...      ...   ...   
4491   35    blue-collar        2          1        0        0        1     0   
4492   32     technician        2          1        0      309        1     1   
4493   28     technician        2          2        0        0        1     0   
4494   26     technician        2          1        0      668        1     0   
4495   48     management        1          2        0     1175        1     0   
4496   30    blue-collar        2          1        0      363        0     0   
4497   31   entrepreneur        2          2        0       38        0     0   
4498   31     management        1          2        0     1183        1     0   
4499   45    blue-collar        0          0        0      942        0     0   
4500   38         admin.        1          1        0     4196        1     0   
4501   34     management        1          2        0      297        1     0   
4502   42       services        1          1        0      -91        1     1   
4503   60  self-employed        1          0        0      362        0     1   
4504   42    blue-collar        2          1        0     1080        1     1   
4505   32         admin.        2          1        0      620        1     0   
4506   42     unemployed        0          2        0     -166        0     0   
4507   33       services        1          1        0      288        1     0   
4508   42         admin.        1    

In [16]:
data.contact.unique()

array(['cellular', 'unknown', 'telephone'], dtype=object)

In [17]:
data['contact'] = data['contact'].astype('category')
data['contact'] = data['contact'].cat.codes
data.contact.unique()

array([0, 2, 1], dtype=int64)

In [18]:
data.month.unique()

array(['oct', 'may', 'apr', 'jun', 'feb', 'aug', 'jan', 'jul', 'nov',
       'sep', 'mar', 'dec'], dtype=object)

In [19]:
data['month'] = data['month'].astype('category')
data['month'] = data['month'].cat.codes
data.month.unique()

array([10,  8,  0,  6,  3,  1,  4,  5,  9, 11,  7,  2], dtype=int64)

In [20]:
data.poutcome.unique()

array(['unknown', 'failure', 'other', 'success'], dtype=object)

In [21]:
data['poutcome'] = data['poutcome'].astype('category')
data['poutcome'] = data['poutcome'].cat.codes
data.poutcome.unique()

array([3, 0, 1, 2], dtype=int64)

In [22]:
data.y.unique()

array(['no', 'yes'], dtype=object)

In [23]:
data['y'] = data['y'].astype('category')

In [24]:
data['y'] = data['y'].cat.codes
data.y.unique()

array([0, 1], dtype=int64)

In [25]:
data

age            job  marital  education  default  balance  housing  loan  \
0      30     unemployed        1          0        0     1787        0     0   
1      33       services        1          1        0     4789        1     1   
2      35     management        2          2        0     1350        1     0   
3      30     management        1          2        0     1476        1     1   
4      59    blue-collar        1          1        0        0        1     0   
5      35     management        2          2        0      747        0     0   
6      36  self-employed        1          2        0      307        1     0   
7      39     technician        1          1        0      147        1     0   
8      41   entrepreneur        1          2        0      221        1     0   
9      43       services        1          0        0      -88        1     1   
10     39       services        1          1        0     9374        1     0   
11     43         admin.        1          1        0      264        1     0   
12     36     technician        1          2        0     1109        0     0   
13     20        student        2          1        0      502        0     0   
14     31    blue-collar        1          1        0      360        1     1   
15     40     management        1          2        0      194        0     1   
16     56     technician        1          1        0     4073        0     0   
17     37         admin.        2          2        0     2317        1     0   
18     25    blue-collar        2          0        0     -221        1     0   
19     31       services        1          1        0      132        0     0   
20     38     management        0          3        0        0        1     0   
21     42     management        0          2        0       16        0     0   
22     44       services        2          1        0      106        0     0   
23     44   entrepreneur        1          1        0       93        0     0   
24     26      housemaid        1          2        0      543        0     0   
25     41     management        1          2        0     5883        0     0   
26     55    blue-collar        1          0        0      627        1     0   
27     67        retired        1          3        0      696        0     0   
28     56  self-employed        1          1        0      784        0     1   
29     53         admin.        1          1        0      105        0     1   
...   ...            ...      ...        ...      ...      ...      ...   ...   
4491   35    blue-collar        2          1        0        0        1     0   
4492   32     technician        2          1        0      309        1     1   
4493   28     technician        2          2        0        0        1     0   
4494   26     technician        2          1        0      668        1     0   
4495   48     management        1          2        0     1175        1     0   
4496   30    blue-collar        2          1        0      363        0     0   
4497   31   entrepreneur        2          2        0       38        0     0   
4498   31     management        1          2        0     1183        1     0   
4499   45    blue-collar        0          0        0      942        0     0   
4500   38         admin.        1          1        0     4196        1     0   
4501   34     management        1          2        0      297        1     0   
4502   42       services        1          1        0      -91        1     1   
4503   60  self-employed        1          0        0      362        0     1   
4504   42    blue-collar        2          1        0     1080        1     1   
4505   32         admin.        2          1        0      620        1     0   
4506   42     unemployed        0          2        0     -166        0     0   
4507   33       services        1          1        0      288        1     0   
4508   42         admin.        1    

In [26]:
data.groupby(["housing","loan"]).size()

housing  loan
0        0       1677
         1        285
1        0       2153
         1        406
dtype: int64

In [27]:
data.previous.unique()

array([ 0,  4,  1,  3,  2,  5, 20,  7,  6, 10,  9,  8, 18, 19, 12, 13, 11,
       14, 15, 24, 17, 22, 23, 25], dtype=int64)

In [28]:
data['previous'] = data['previous'].astype('category')
data.previous.unique()

[0, 4, 1, 3, 2, ..., 24, 17, 22, 23, 25]
Length: 24
Categories (24, int64): [0, 4, 1, 3, ..., 17, 22, 23, 25]

In [29]:
data.groupby(["education","loan"]).size()

education  loan
0          0        584
           1         94
1          0       1890
           1        416
2          0       1176
           1        174
3          0        180
           1          7
dtype: int64

In [30]:
from pgmpy.models import MarkovModel

In [31]:
from pgmpy.factors.discrete import DiscreteFactor

In [32]:
mark = MarkovModel([('education','loan'),('education','housing'),('loan','y'),('housing','y'),('marital','y'),('default','y'),('contact','month'),('month','y')])

In [33]:
data.groupby(["education","loan"]).size()

education  loan
0          0        584
           1         94
1          0       1890
           1        416
2          0       1176
           1        174
3          0        180
           1          7
dtype: int64

In [34]:
f1 = DiscreteFactor(["education","loan"],cardinality=[4,2],values=(584,94,1890,416,1176,174,180,7))

In [35]:
data.groupby(["education","housing"]).size()

education  housing
0          0           295
           1           383
1          0           876
           1          1430
2          0           687
           1           663
3          0           104
           1            83
dtype: int64

In [36]:
f2 = DiscreteFactor(["education","housing"],cardinality=[4,2],values=(295,383,876,1430,687,663,104,83))

In [37]:
data.groupby(["loan","y"]).size()

loan  y
0     0    3352
      1     478
1     0     648
      1      43
dtype: int64

In [38]:
f3 = DiscreteFactor(["loan","y"],cardinality=[2,2],values=(3352,478,648,43))

In [39]:
data.groupby(["housing","y"]).size()

housing  y
0        0    1661
         1     301
1        0    2339
         1     220
dtype: int64

In [40]:
f4 = DiscreteFactor(["housing","y"],cardinality=[2,2],values=(1661,301,2339,220))

In [41]:
data.groupby(["marital","y"]).size()

marital  y
0        0     451
         1      77
1        0    2520
         1     277
2        0    1029
         1     167
dtype: int64

In [42]:
f5 = DiscreteFactor(["marital","y"],cardinality=[3,2],values=(451,77,2520,277,1029,167))

In [43]:
data.groupby(["default","y"]).size()

default  y
0        0    3933
         1     512
1        0      67
         1       9
dtype: int64

In [44]:
f6 = DiscreteFactor(["default","y"],cardinality=[2,2],values=(3933,512,67,9))

In [45]:
data.groupby(["contact","previous"]).size()

contact  previous
0        0           2164
         1            262
         2            169
         3            102
         4             71
         5             42
         6             21
         7             19
         8             16
         9             10
         10             4
         11             2
         12             2
         13             1
         14             2
         15             1
         17             1
         18             1
         19             1
         20             1
         22             1
         23             1
         24             1
         25             1
1        0            228
         1             23
         2             20
         3              9
         4              6
         5              4
         6              3
         7              3
         8              2
         11             1
         12             2
2        0           1313
         1              1
         2          

In [46]:
data.groupby(["contact","month"]).size()

contact  month
0        0        276
         1        607
         2         18
         3        199
         4        129
         5        576
         6         73
         7         38
         8        529
         9        345
         10        64
         11        42
1        0         17
         1         20
         2          2
         3         23
         4         18
         5        102
         6          8
         7         10
         8         49
         9         38
         10        11
         11         3
2        1          6
         4          1
         5         28
         6        450
         7          1
         8        820
         9          6
         10         5
         11         7
dtype: int64

In [47]:
f7 = DiscreteFactor(["contact","month"],cardinality=[3,12],values=(276,607,18,199,129,576,73,38,529,345,64,42,17,20,2,23,18,102,8,10,49,38,11,3,0,6,0,0,1,28,450,1,820,6,5,7))

In [48]:
data.groupby(["month","y"]).size()

month  y
0      0     237
       1      56
1      0     554
       1      79
2      0      11
       1       9
3      0     184
       1      38
4      0     132
       1      16
5      0     645
       1      61
6      0     476
       1      55
7      0      28
       1      21
8      0    1305
       1      93
9      0     350
       1      39
10     0      43
       1      37
11     0      35
       1      17
dtype: int64

In [49]:
f8 = DiscreteFactor(["month","y"],cardinality=[12,2],values=(237,56,554,79,11,9,184,38,132,16,645,61,476,55,28,21,1305,93,350,39,43,37,35,17))

In [50]:
data.groupby(["poutcome","y"]).size()

poutcome  y
0         0     427
          1      63
1         0     159
          1      38
2         0      46
          1      83
3         0    3368
          1     337
dtype: int64

In [51]:
f9 = DiscreteFactor(["poutcome","y"],cardinality=[4,2],values=(427,63,159,38,46,83,3368,337))

In [52]:
mark.add_factors(f1)

In [53]:
mark.add_factors(f2)
mark.add_factors(f3)
mark.add_factors(f3)
mark.add_factors(f4)
mark.add_factors(f5)
mark.add_factors(f6)
mark.add_factors(f7)
mark.add_factors(f8)
#mark.add_factors(f9)

In [54]:
mark.get_local_independencies()

(default _|_ month, loan, marital, contact, education, housing | y)
(loan _|_ default, housing, contact, marital, month | y, education)
(marital _|_ default, loan, month, contact, education, housing | y)
(contact _|_ default, loan, marital, y, education, housing | month)
(month _|_ default, loan, education, housing, marital | y, contact)
(y _|_ contact, education | default, loan, month, housing, marital)
(education _|_ default, y, contact, marital, month | loan, housing)
(housing _|_ default, loan, contact, month, marital | y, education)

In [55]:
from pgmpy.inference import Mplp

In [56]:
mplp = Mplp(mark)

In [57]:
mplp.find_triangles()

[]

In [58]:
mplp.map_query()

KeyError: frozenset(['loan'])

In [59]:
from pgmpy.estimators import MaximumLikelihoodEstimator, BayesianEstimator
from pgmpy.sampling import BayesianModelSampling
from pgmpy.factors.discrete import State
from pgmpy.inference import BeliefPropagation
from pgmpy.models import BayesianModel

In [60]:
infer1 = BayesianModelSampling(mark)
evidence1 = [State('y',1)]
sample1 = infer1.forward_sample(5)
sample1

TypeError: ('Model expected type: BayesianModel, got type: ', <class 'pgmpy.models.MarkovModel.MarkovModel'>)

In [61]:
belief_prop = BeliefPropagation(mark)

In [62]:
bp1 = belief_prop.query(variables=['y'],evidence={'marital' : 2,'default' : 0})
print(bp1['y'])

+-----+----------+
| y   |   phi(y) |
|-----+----------|
| y_0 |   1.0000 |
| y_1 |   0.0000 |
+-----+----------+


In [63]:
bp2 = belief_prop.query(variables=['y'],evidence={'education' : 2,'housing' : 1})
print(bp2['y'])

+-----+----------+
| y   |   phi(y) |
|-----+----------|
| y_0 |   1.0000 |
| y_1 |   0.0000 |
+-----+----------+


In [64]:
bp3 = belief_prop.query(variables=['y'],evidence={'month' : 11,'poutcome' : 2})
print(bp3['y'])

KeyError: 'poutcome'

In [65]:
bp4 = belief_prop.query(variables=['y'],evidence={'contact' : 2})
print(bp4['y'])

+-----+----------+
| y   |   phi(y) |
|-----+----------|
| y_0 |   1.0000 |
| y_1 |   0.0000 |
+-----+----------+


In [66]:
bp5 = belief_prop.query(variables=['y'],evidence={'poutcome' : 2, 'loan' : 1})
print(bp5['y'])

KeyError: 'poutcome'

In [67]:
from pgmpy.inference import VariableElimination
infer = VariableElimination(mark)

In [68]:
infer.query(['loan','housing'])

{'housing': <DiscreteFactor representing phi(housing:2) at 0xa2d89b0L>,
 'loan': <DiscreteFactor representing phi(loan:2) at 0xa2d8b00L>}

In [69]:
from pgmpy.models import MarkovModel
#gibbs_chain = GibbsSampling(student)

In [70]:
import pgmpy

In [71]:
from pgmpy.sampling import GibbsSampling

In [72]:
gibbs_chain = GibbsSampling(mark)

In [73]:
gibbs_chain

In [74]:
gen = gibbs_chain.generate_sample(size=5)

In [75]:
gen

<generator object generate_sample at 0x000000000A2DF870>

In [76]:
[sample for sample in gen]

KeyError: 'default'

In [77]:
gibbs_chain.sample(size=5)

KeyError: 'default'

In [106]:
data

age            job  marital  education  default  balance  housing  loan  \
0      30     unemployed        1          0        0     1787        0     0   
1      33       services        1          1        0     4789        1     1   
2      35     management        2          2        0     1350        1     0   
3      30     management        1          2        0     1476        1     1   
4      59    blue-collar        1          1        0        0        1     0   
5      35     management        2          2        0      747        0     0   
6      36  self-employed        1          2        0      307        1     0   
7      39     technician        1          1        0      147        1     0   
8      41   entrepreneur        1          2        0      221        1     0   
9      43       services        1          0        0      -88        1     1   
10     39       services        1          1        0     9374        1     0   
11     43         admin.        1          1        0      264        1     0   
12     36     technician        1          2        0     1109        0     0   
13     20        student        2          1        0      502        0     0   
14     31    blue-collar        1          1        0      360        1     1   
15     40     management        1          2        0      194        0     1   
16     56     technician        1          1        0     4073        0     0   
17     37         admin.        2          2        0     2317        1     0   
18     25    blue-collar        2          0        0     -221        1     0   
19     31       services        1          1        0      132        0     0   
20     38     management        0          3        0        0        1     0   
21     42     management        0          2        0       16        0     0   
22     44       services        2          1        0      106        0     0   
23     44   entrepreneur        1          1        0       93        0     0   
24     26      housemaid        1          2        0      543        0     0   
25     41     management        1          2        0     5883        0     0   
26     55    blue-collar        1          0        0      627        1     0   
27     67        retired        1          3        0      696        0     0   
28     56  self-employed        1          1        0      784        0     1   
29     53         admin.        1          1        0      105        0     1   
...   ...            ...      ...        ...      ...      ...      ...   ...   
4491   35    blue-collar        2          1        0        0        1     0   
4492   32     technician        2          1        0      309        1     1   
4493   28     technician        2          2        0        0        1     0   
4494   26     technician        2          1        0      668        1     0   
4495   48     management        1          2        0     1175        1     0   
4496   30    blue-collar        2          1        0      363        0     0   
4497   31   entrepreneur        2          2        0       38        0     0   
4498   31     management        1          2        0     1183        1     0   
4499   45    blue-collar        0          0        0      942        0     0   
4500   38         admin.        1          1        0     4196        1     0   
4501   34     management        1          2        0      297        1     0   
4502   42       services        1          1        0      -91        1     1   
4503   60  self-employed        1          0        0      362        0     1   
4504   42    blue-collar        2          1        0     1080        1     1   
4505   32         admin.        2          1        0      620        1     0   
4506   42     unemployed        0          2        0     -166        0     0   
4507   33       services        1          1        0      288        1     0   
4508   42         admin.        1    

In [ ]:
mark1 = 